
import Queueing.OperationFileAttente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.*;

/*
 * Copyright (C) 2016 hux
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 *
 * @author hux
 */
public class Windows extends javax.swing.JFrame {

    /**
     * Creates new form Windows
     */
    public Windows() {
        initComponents();
        //le premier type de liste est MM1 par défaut
        //donc on masque les champs non nécéssaire
        jLabelNbClient.setVisible(false);
        jLabelNbServeur.setVisible(false);
        varNbClient.setVisible(false);
        varNbServer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTypeFile = new javax.swing.JLabel();
        varTypeFile = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextPane();
        jLabelResult = new javax.swing.JLabel();
        jLabelLambda = new javax.swing.JLabel();
        jLabelMu = new javax.swing.JLabel();
        jLabelNbClient = new javax.swing.JLabel();
        jLabelNbServeur = new javax.swing.JLabel();
        varNbServer = new javax.swing.JTextField();
        varNbClient = new javax.swing.JTextField();
        varMu = new javax.swing.JTextField();
        varLambda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        varEtat = new javax.swing.JTextField();
        jLabelEtat = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        varTemps = new javax.swing.JTextField();
        jLabelInstant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Queueing/Windows"); // NOI18N
        setTitle(bundle.getString("TITLE")); // NOI18N
        setMinimumSize(new java.awt.Dimension(708, 450));

        jLabelTypeFile.setText(bundle.getString("LABEL_CHOICE")); // NOI18N

        varTypeFile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM1", "MM1K", "MMS" }));
        varTypeFile.setToolTipText("");
        varTypeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select(evt);
            }
        });

        content.setEditable(false);
        jScrollPane1.setViewportView(content);

        jLabelResult.setText(bundle.getString("LABEL_RESULT")); // NOI18N

        jLabelLambda.setText(bundle.getString("LABEL_LAMBDA")); // NOI18N

        jLabelMu.setText(bundle.getString("LABEL_MU")); // NOI18N

        jLabelNbClient.setText(bundle.getString("LABEL_NB_CUSTOMER")); // NOI18N

        jLabelNbServeur.setText(bundle.getString("LABEL_NB_SERVER")); // NOI18N

        jButton1.setText(bundle.getString("SOUMETTRE")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelEtat.setText(bundle.getString("LABEL_STATE")); // NOI18N
        jLabelEtat.setToolTipText("");

        jButton2.setText(bundle.getString("REINITIALIZE_BUTTON")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelInstant.setText(bundle.getString("LABEL_INSTANT")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTypeFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varTypeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 367, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelNbClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelNbServeur, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(varNbServer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(varNbClient, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelLambda)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(varLambda))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelMu)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(varMu, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelEtat, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelResult))
                                .addComponent(varEtat)
                                .addComponent(varTemps))
                            .addComponent(jLabelInstant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTypeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varTypeFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLambda))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMu)
                            .addComponent(varMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNbClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varNbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNbServeur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varNbServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInstant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varTemps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sAffichage = "";
        sTypeFile = (String) varTypeFile.getSelectedItem();
        try {
            dLambda = Double.parseDouble(varLambda.getText());
        } catch (NumberFormatException e) {
            try {
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine engine = mgr.getEngineByName(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("JAVASCRIPT"));
                System.out.println(engine.eval(varLambda.getText()));
                dLambda = (double) engine.eval(varLambda.getText());
            } catch (ScriptException ex) {
                Logger.getLogger(Windows.class.getName()).log(Level.SEVERE, java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_SCRIPT"), ex);
                content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_LAMBDA_PARAMETER"));
            }
        }
        try {
            dMu = Double.parseDouble(varMu.getText());
        } catch (NumberFormatException e) {
            content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_MU_PARAMETER"));
        }
        try {
            iNbServer = Integer.parseInt(varNbServer.getText());
        } catch (NumberFormatException e) {
            if (!java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1").equals(sTypeFile) && !java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1K").equals(sTypeFile)) {
                content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_NB_SERVER_PARAMTER"));
            }
        }
        try {
            if (!java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1").equals(sTypeFile)) {
                iNbClient = Integer.parseInt(varNbClient.getText());
            }
        } catch (NumberFormatException e) {
            content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_NB_CUSTOMER_PARAMTER"));
        }
        try {
            iEtat = Integer.parseInt(varEtat.getText());
        } catch (NumberFormatException e) {
            content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_BAD_STATE_PARAMETER"));
        }
        try {
            dT = Double.parseDouble(varTemps.getText());
        } catch (NumberFormatException e) {
            try {
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine engine = mgr.getEngineByName(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("JAVASCRIPT"));
                System.out.println(engine.eval(varTemps.getText()));
                dT = (double) engine.eval(varTemps.getText());
            } catch (ScriptException ex) {
                Logger.getLogger(Windows.class.getName()).log(Level.SEVERE, java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR SCRIPT"), ex);
                content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("ERREUR_BAD_t_PARAMETER"));
            }
        }

        if (sTypeFile != null && !"".equals(sTypeFile) && dLambda != 0.0 && dMu != 0.0 && ((iNbServer != 0 && iNbClient != 0 && java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MMS").equals(sTypeFile)) || (iNbClient != 0 && java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1K").equals(sTypeFile)) || java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1").equals(sTypeFile))) {
            sAffichage = content.getText();
            sAffichage += "\n" + OperationFileAttente.calcul(iNbServer, iNbClient, dMu, dLambda, sTypeFile, iEtat, dT);
            content.setText(sAffichage);
        } else {

            content.setText(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("WARNING_PARAMETER_NOTSET"));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        varEtat.setText("");
        varLambda.setText("");
        varMu.setText("");
        varNbClient.setText("");
        varNbServer.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void select(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select
        if (((String) varTypeFile.getSelectedItem()).equals(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1"))) {
            jLabelNbClient.setVisible(false);
            jLabelNbServeur.setVisible(false);
            varNbClient.setVisible(false);
            varNbServer.setVisible(false);
        } else if (((String) varTypeFile.getSelectedItem()).equals(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MM1K"))) {
            jLabelNbClient.setVisible(true);
            jLabelNbServeur.setVisible(false);
            varNbClient.setVisible(true);
            varNbServer.setVisible(false);
        } else if (((String) varTypeFile.getSelectedItem()).equals(java.util.ResourceBundle.getBundle("Queueing/Windows").getString("LABEL_MMS"))) {
            jLabelNbClient.setVisible(true);
            jLabelNbServeur.setVisible(true);
            varNbClient.setVisible(true);
            varNbServer.setVisible(true);
        }

    }//GEN-LAST:event_select

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("Queueing/Windows").getString("DESIGN").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Windows.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Windows.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Windows.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Windows.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Windows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelEtat;
    private javax.swing.JLabel jLabelInstant;
    private javax.swing.JLabel jLabelLambda;
    private javax.swing.JLabel jLabelMu;
    private javax.swing.JLabel jLabelNbClient;
    private javax.swing.JLabel jLabelNbServeur;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelTypeFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField varEtat;
    private javax.swing.JTextField varLambda;
    private javax.swing.JTextField varMu;
    private javax.swing.JTextField varNbClient;
    private javax.swing.JTextField varNbServer;
    private javax.swing.JTextField varTemps;
    private javax.swing.JComboBox<String> varTypeFile;
    // End of variables declaration//GEN-END:variables
    double dMu = 0.0;
    double dLambda = 0.0;
    int iNbServer = 0;
    int iNbClient = 0;
    int iEtat = 0;
    double dT = 0.0;
    String sTypeFile = "";
}
